# version: '3.1'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: qr_payment_app
#     environment:
#       - APP_NAME=${APP_NAME}
#       - APP_ENV=${APP_ENV}
#       - APP_KEY=${APP_KEY}
#       - APP_DEBUG=${APP_DEBUG}
#       - APP_URL=${APP_URL}
#       - DB_HOST=${DB_HOST}
#       - DB_PORT=${DB_PORT}
#       - DB_DATABASE=${DB_DATABASE}
#       - DB_USERNAME=${DB_USERNAME}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - REDIS_HOST=${REDIS_HOST}
#       - REDIS_PORT=${REDIS_PORT}
#     ports:
#       - "5000:80"
#     depends_on:
#       - db
#       - redis
#     volumes:
#       - ./app:/app
#     networks:
#       - default

#   db:
#     image: postgres:13
#     container_name: db_postrgres
#     environment:
#       - POSTGRES_DB=${DB_DATABASE}
#       - POSTGRES_USER=${DB_USERNAME}
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#     ports:
#       - 6000:5432
#     restart: always
#     networks:
#       - default

#   redis:
#     image: redis:latest
#     container_name: redis
#     ports:
#       - "6379:6379"
#     restart: always
#     networks:
#       - default

#   supervisor:  # Добавление сервиса Supervisor
#     build:
#       context: .
#       dockerfile: Dockerfile  # Используем тот же Dockerfile, который уже настроен
#     volumes:
#       - ./app:/app
#     command: supervisord -c /etc/supervisor/conf.d/supervisord.conf  # Команда для запуска Supervisor
#     restart: unless-stopped
#     networks:
#       - default

# networks:
#     default:
#         driver: bridge


