name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USER }}
          key: ${{ secrets.BEGET_PRIVATE_KEY }}
          scritp: |

            cd /home/x/xpystum/xpystum.beget.tech && sh ./deploy.sh


